version: '3.4'

services:
  expressapi:
    image: expressapi
    build:
      context: ./.docker/services
      dockerfile: ./node/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "src/index.ts"]
